//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThucPhamSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANGCAO
    {
        public int MAQC { get; set; }
        public string TENQC { get; set; }
        public string ANHQC { get; set; }
        public string HREF { get; set; }
        public Nullable<short> THUTUQC { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    }
}
