//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThucPhamSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string ANHSP { get; set; }
        public string XUATSU { get; set; }
        public string MOTA { get; set; }
        public Nullable<decimal> GIASP { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
        public Nullable<short> SPMOI { get; set; }
        public Nullable<int> MADM { get; set; }
        public Nullable<int> LUOTXEM { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
    }
}
